### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 쿠폰 정책 등록 1
POST http://localhost:8083/api/coupon-policies
Content-Type: application/json

{
  "name": "SALE_COUPON",
  "saleType": "AMOUNT",
  "minimumAmount": 100.0,
  "discountLimit": 5000.0,
  "discountRatio": 0,
  "isStackable": true,
  "couponScope": "ALL",
  "startDate": "2025-01-01T00:00:00",
  "endDate": "2025-12-31T23:59:59",
  "couponActive": true
}

### 쿠폰 정책 등록 2
POST http://localhost:8083/api/coupon-policies
Content-Type: application/json

{
  "name": "SALE_COUPON_RATIO",
  "saleType": "RATIO",
  "minimumAmount": 100.0,
  "discountLimit": 5000.0,
  "discountRatio": 10,
  "isStackable": true,
  "couponScope": "BOOK",
  "startDate": "2025-01-01T00:00:00",
  "endDate": "2025-12-31T23:59:59",
  "couponActive": true
}

### 쿠폰 정책 등록 3
POST http://localhost:8083/api/coupon-policies
Content-Type: application/json

{
  "name": "EXPIRED_COUPON_RATIO",
  "saleType": "RATIO",
  "minimumAmount": 100.0,
  "discountLimit": 5000.0,
  "discountRatio": 10,
  "isStackable": true,
  "couponScope": "BOOK",
  "startDate": "2024-12-01T00:00:00",
  "endDate": "2024-12-31T23:59:59",
  "couponActive": true
}

### 유효한 쿠폰 정책 조회
GET http://localhost:8083/api/coupon-policies?couponActive=true&page=0&pageSize=10
Content-Type: application/json

### 쿠폰정책 ID로 검색
GET http://localhost:8083/api/coupon-policies/51
Content-Type: application/json

### 쿠폰정책 이름으로 검색
GET http://localhost:8083/api/coupon-policies/search?name=SALE_COUPON
Content-Type: application/json

### 쿠폰정책에 쿠폰대상 추가
POST http://localhost:8083/api/coupon-policies/65/targets
Content-Type: application/json

{
  "ctTargetId": 108
}