### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

### 회원에게 쿠폰 발급 -
POST http://localhost:8083/api/member-coupons
Content-Type: application/json

{
  "mcMemberId": 108,
  "couponId": 57
}

### 회원 ID로 회원 쿠폰 조회
GET http://localhost:8083/api/member-coupons/member/108

### 회원이 사용 가능한 쿠폰 목록 조회
GET http://localhost:8083/api/member-coupons/member/108/unused
